# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='medical_examination_id',
            new_name='medical_examination',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='room_id',
            new_name='room',
        ),
    ]
